version: '3.8'

services:
  auth-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: authdb
    ports:
      - '5433:5432'
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  auth-redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    command: sleep infinity
    environment:
      DB_HOST: auth-db
      DB_PORT: 5432
      DB_USER: authuser
      DB_PASSWORD: secret
      DB_NAME: authdb
      REDIS_HOST: auth-redis
      REDIS_PORT: 6379
    ports:
      - '50051:50051'
    volumes:
      - ./:/workspace
    depends_on:
      - auth-db
      - auth-redis
