version: '3.8'

services:
  auth-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: authdb
    ports:
      - '5433:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-redis:
    image: redis:7
    restart: always
    ports:
      - '6379:6379'

  auth-service:
    build:
      context: ./
    ports:
      - '50051:50051'
    depends_on:
      - auth-db
      - auth-redis
    env_file:
      - ./.env
